In [1]:
import numpy as np

A = np.array([[1, 2, 4], [2, 3, 8], [-1, -3, -1]])

# QR-Zerlegung
Q, R = np.linalg.qr(A)

# Probe: A = QR
probe = np.matmul(Q, R)

print("Matrix A:")
print(A)
print("\nQR-Zerlegung:")
print("Q:")
print(Q)
print("R:")
print(R)
print("Probe A = QR:")
print(probe)

Matrix A:
[[ 1  2  4]
 [ 2  3  8]
 [-1 -3 -1]]

QR-Zerlegung:
Q:
[[-0.40824829  0.12309149  0.90453403]
 [-0.81649658 -0.49236596 -0.30151134]
 [ 0.40824829 -0.86164044  0.30151134]]
R:
[[-2.44948974 -4.4907312  -8.5732141 ]
 [ 0.          1.3540064  -2.58492131]
 [ 0.          0.          0.90453403]]

Probe A = QR:
[[ 1.  2.  4.]
 [ 2.  3.  8.]
 [-1. -3. -1.]]


In [4]:
import numpy as np

def approximate_diagonal_matrix_iteration(A):
    An = np.copy(A)
    U_matrices = []

    for iteration in range(1000):
        # QR decomposition
        Q, R = np.linalg.qr(An)
        U_matrices.append(Q)
        # Update An+1 = R * Q
        An = np.dot(R, Q)

        # Check for diagonal dominance
        #off_diagonal_sum = np.sum(np.abs(An - np.diag(np.diagonal(An))))
        
        #if off_diagonal_sum < tolerance:
            #break
    for Q in U_matrices:
        
    return An, U


A_prime_approx = approximate_diagonal_matrix_iteration(A)

print("Original Matrix A:")
print(A)
print("\nApproximated Diagonal-Dominant Matrix A' after Iterations:")
print(A_prime_approx)

Original Matrix A:
[[ 1  2  4]
 [ 2  3  8]
 [-1 -3 -1]]

Approximated Diagonal-Dominant Matrix A' after Iterations:
[[ 3.44854489 -9.32139336 -1.71939183]
 [ 2.62898025 -0.32034543  0.48193578]
 [ 0.          0.         -0.12819947]]


In [5]:
B = np.array([[2, -1], [-1, 4]])

# Anwenden der Funktion auf Matrix B
B_prime, U_B = approximate_diagonal_matrix(B)

# Probe: B = UB'U^T
probe_B = np.matmul(np.matmul(U_B, B_prime), U_B.T)

# Vergleich der Approximation mit numpy.linalg.eigvals
eigenvalues_B_approx = np.diagonal(B_prime)
eigenvalues_B_exact = np.linalg.eigvals(B)

print("\nMatrix B:")
print(B)
print("\nMatrix B' (approximated):")
print(B_prime)
print("\nProbe B = UB'U^T:")
print(probe_B)
print("\nApproximierte Eigenwerte von B:")
print(eigenvalues_B_approx)
print("\nExakte Eigenwerte von B (numpy.linalg.eigvals):")
print(eigenvalues_B_exact)

NameError: name 'approximate_diagonal_matrix' is not defined